# Generated by Django 2.2.9 on 2020-01-26 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20200126_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client', to='shop.Client'),
        ),
    ]
